# Generated by Django 5.2.5 on 2025-11-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrating',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientrating',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='gigseeker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='gigseeker',
            name='verified_by',
        ),
        migrations.RemoveField(
            model_name='gigseekerrating',
            name='gig_seeker',
        ),
        migrations.RemoveField(
            model_name='gigseekerrating',
            name='created_by',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='country',
            new_name='occupation',
        ),
        migrations.AddField(
            model_name='user',
            name='account_locked_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_failed_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='origin_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='resident_country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='visit_type',
            field=models.CharField(blank=True, choices=[('STUDY', 'STUDY'), ('BUSINESS', 'BUSINESS'), ('PERSONAL', 'PERSONAL'), ('TOURIST', 'TOURIST'), ('RELOCATION', 'RELOCATION'), ('OTHER', 'OTHER')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'customer'), ('super_admin', 'super_admin')], max_length=15),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientRating',
        ),
        migrations.DeleteModel(
            name='GigSeeker',
        ),
        migrations.DeleteModel(
            name='GigSeekerRating',
        ),
    ]
