# Generated by Django 5.2.5 on 2025-11-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_clientrating_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetimepassword',
            name='has_expired',
            field=models.BooleanField(default=False),
        ),
    ]
