# Generated by Django 5.2.5 on 2026-06-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_onetimepassword_has_expired'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('admin', 'admin'), ('customer', 'customer'), ('super_admin', 'super_admin'), ('operator', 'operator')], max_length=15),
        ),
    ]
