# Generated by Django 5.2.5 on 2026-06-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usd_amount', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('credit_amount', models.IntegerField(default=10, help_text='Number of credits given per usd_amount')),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='e.g., NGN, RWF, EUR', max_length=10, unique=True)),
                ('rate_to_usd', models.DecimalField(decimal_places=6, help_text='Amount of this currency that equals 1 USD', max_digits=14)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('UI', 'User Interface (Credits)'), ('API', 'Developer API (Metered USD)')], max_length=10)),
                ('translation_type', models.CharField(choices=[('STS', 'Speech to Speech'), ('STT', 'Speech to Text'), ('TTT', 'Text to Text'), ('TTS', 'Text to Speech'), ('DOC', 'Document Translation')], max_length=10)),
                ('unit_name', models.CharField(help_text='e.g., minute, million_chars, page', max_length=50)),
                ('cost_per_unit', models.DecimalField(decimal_places=6, help_text='If channel is UI, this is in Credits. If API, this is in USD.', max_digits=14)),
            ],
            options={
                'unique_together': {('channel', 'translation_type')},
            },
        ),
    ]
