# Generated by Django 5.2.6 on 2025-09-28 11:39

import core.model
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archived",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("reference", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("SUCCESS", "SUCCESS"),
                            ("FAILED", "FAILED"),
                        ],
                        default="PENDING",
                        max_length=100,
                    ),
                ),
                (
                    "payment_type",
                    models.CharField(
                        choices=[
                            ("NEW_SERVICE", "NEW_SERVICE"),
                            ("SUBSCRIPTION", "SUBSCRIPTION"),
                        ],
                        default="NEW_SERVICE",
                        max_length=100,
                    ),
                ),
                (
                    "payment_channel",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "gateway_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "service_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
            ],
            options={
                "ordering": ["-last_modified"],
                "abstract": False,
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
    ]
