# Generated by Django 5.2.5 on 2026-03-20 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPayWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refid', models.CharField(db_index=True, max_length=100)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status_id', models.CharField(max_length=10)),
                ('status_desc', models.TextField()),
                ('raw_payload', models.JSONField()),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['refid'], name='payment_kpa_refid_23fe28_idx')],
            },
        ),
    ]
