# Generated by Django 5.2.6 on 2025-09-28 11:39

import core.model
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "archived",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("last_modified", models.DateTimeField(auto_now=True)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("SMSM", "SMS"),
                            ("EMAIL", "EMAIL"),
                            ("WHATSAPP", "WHATSAPP"),
                        ],
                        max_length=255,
                    ),
                ),
                ("status", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_modified"],
                "abstract": False,
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
    ]
