# Generated by Django 5.2.6 on 2025-11-02 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notificationplatform",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="notificationplatform",
            name="updated_at",
        ),
    ]
