# Generated by Django 5.2.5 on 2025-11-08 14:01

import core.model
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='ocr_images/')),
                ('image_url', models.URLField(blank=True, help_text='Cloud storage URL for uploaded image', null=True)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename of uploaded image', max_length=255, null=True)),
                ('image_format', models.CharField(blank=True, help_text='Image file format (jpg, png, etc.)', max_length=10, null=True)),
                ('original_text', models.TextField(blank=True, null=True)),
                ('detected_language', models.CharField(blank=True, max_length=10, null=True)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('translation_provider', models.CharField(blank=True, choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('anthropic', 'Anthropic Claude'), ('gemini_legacy', 'Gemini Legacy'), ('auto', 'Automatic Selection')], help_text='Translation service that was used for this request', max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
        migrations.CreateModel(
            name='TranslationFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('source_text', models.TextField(help_text='Original text that failed to translate')),
                ('source_language', models.CharField(blank=True, max_length=10, null=True)),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('attempted_provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('anthropic', 'Anthropic Claude'), ('gemini_legacy', 'Gemini Legacy'), ('auto', 'Automatic Selection')], help_text='Translation service that failed', max_length=20)),
                ('error_message', models.TextField(help_text='Detailed error message from the provider')),
                ('error_type', models.CharField(choices=[('api_error', 'API Error'), ('timeout', 'Request Timeout'), ('auth_error', 'Authentication Error'), ('quota_exceeded', 'Quota Exceeded'), ('invalid_input', 'Invalid Input'), ('network_error', 'Network Error'), ('unknown', 'Unknown Error')], default='unknown', max_length=50)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('fallback_used', models.BooleanField(default=False, help_text='Whether fallback service was used')),
                ('fallback_provider', models.CharField(blank=True, max_length=20, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('ocr_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_failures', to='ocr_app.ocrresult')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_failures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Translation Failure Log',
                'verbose_name_plural': 'Translation Failure Logs',
                'db_table': 'translation_failure_logs',
                'ordering': ['-date_created'],
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
    ]
