# Generated by Django 5.2.5 on 2025-08-31 11:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OCRResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='ocr_images/')),
                ('image_url', models.URLField(blank=True, help_text='Cloud storage URL for uploaded image', null=True)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename of uploaded image', max_length=255, null=True)),
                ('image_format', models.CharField(blank=True, help_text='Image file format (jpg, png, etc.)', max_length=10, null=True)),
                ('original_text', models.TextField(blank=True, null=True)),
                ('detected_language', models.CharField(blank=True, max_length=10, null=True)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_time', models.FloatField(blank=True, null=True)),
                ('translation_provider', models.CharField(blank=True, choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('anthropic', 'Anthropic Claude'), ('gemini_legacy', 'Gemini Legacy'), ('auto', 'Automatic Selection')], help_text='Translation service that was used for this request', max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranslationFailureLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('source_text', models.TextField(help_text='Original text that failed to translate')),
                ('source_language', models.CharField(blank=True, max_length=10, null=True)),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('attempted_provider', models.CharField(choices=[('gemini', 'Google Gemini'), ('openai', 'OpenAI GPT'), ('anthropic', 'Anthropic Claude'), ('gemini_legacy', 'Gemini Legacy'), ('auto', 'Automatic Selection')], help_text='Translation service that failed', max_length=20)),
                ('error_message', models.TextField(help_text='Detailed error message from the provider')),
                ('error_type', models.CharField(choices=[('api_error', 'API Error'), ('timeout', 'Request Timeout'), ('auth_error', 'Authentication Error'), ('quota_exceeded', 'Quota Exceeded'), ('invalid_input', 'Invalid Input'), ('network_error', 'Network Error'), ('unknown', 'Unknown Error')], default='unknown', max_length=50)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('fallback_used', models.BooleanField(default=False, help_text='Whether fallback service was used')),
                ('fallback_provider', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Translation Failure Log',
                'verbose_name_plural': 'Translation Failure Logs',
                'db_table': 'translation_failure_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
