# Generated by Django 5.2.5 on 2025-08-31 11:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ocr_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ocr_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='translationfailurelog',
            name='ocr_result',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_failures', to='ocr_app.ocrresult'),
        ),
        migrations.AddField(
            model_name='translationfailurelog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translation_failures', to=settings.AUTH_USER_MODEL),
        ),
    ]
