# Generated by Django 5.2.5 on 2025-11-08 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocr_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocrresult',
            name='feature_type',
            field=models.CharField(blank=True, default='IMAGE_TRANSLATION', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='language_detection_time',
            field=models.FloatField(blank=True, help_text='Time for language detection', null=True),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='ocr_processing_time',
            field=models.FloatField(blank=True, help_text='Time for OCR step', null=True),
        ),
        migrations.AddField(
            model_name='ocrresult',
            name='translation_processing_time',
            field=models.FloatField(blank=True, help_text='Time for translation step', null=True),
        ),
        migrations.AlterField(
            model_name='ocrresult',
            name='processing_time',
            field=models.FloatField(blank=True, help_text='Total processing time in seconds', null=True),
        ),
    ]
