"""
Django settings for echo project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path
from decouple import config
import datetime


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!


# Application definition

INSTALLED_DEFAULT_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "daphne",
    "django.contrib.staticfiles",
]


INSTALLED_THIRD_PARTY_APPS = [
  
    "channels",
    "rest_framework",
    "django_filters",
    "corsheaders",
    "drf_spectacular",
    "drf_spectacular_sidecar",  # Optional: for UI (Swagger/Redoc)
    "django_extensions",
    "rest_framework_simplejwt",
    "rest_framework.authtoken",
    "cloudinary",
    "cloudinary_storage",
    # "allauth",
    # "allauth.account",
    # "allauth.socialaccount",
    # "dj_rest_auth",
    # "dj_rest_auth.registration",
]

INTERNAL_APPS = [
    'users',
    'ocr_app',
    'translation',
    'stats_app',
    'realtime',
    'performance',
    'notification',
    'payment',
    'wallet'
]


INSTALLED_APPS = INSTALLED_DEFAULT_APPS + INSTALLED_THIRD_PARTY_APPS + INTERNAL_APPS


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # 'allauth.account.middleware.AccountMiddleware',
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.LogRequest",
    "core.middleware.UpdateLastLoginMiddleware",
]


REST_FRAMEWORK_DEFAULT_AUTH = (
    "rest_framework_simplejwt.authentication.JWTAuthentication",
    "rest_framework.authentication.SessionAuthentication",
    "rest_framework.authentication.TokenAuthentication",
    "rest_framework.authentication.BasicAuthentication",
)

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (REST_FRAMEWORK_DEFAULT_AUTH),
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.FormParser',
    ],
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS": "core.utils.helper.CustomPagination",
    "PAGE_SIZE": 20,
    "PAGE_SIZE_PARAM": "page_size",
    # Total number of rows on a worksheet (since Excel 2007)
    # https://support.office.com/en-us/article/Excel-specifications-and-limits-1672b34d-7043-467e-8e27-269d656771c3
    "MAX_PAGE_SIZE": int(config("MAX_PAGE_SIZE", 1048574)),
    "NON_FIELD_ERRORS_KEY": "error",
}


SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": datetime.timedelta(minutes=2880),
    "REFRESH_TOKEN_LIFETIME": datetime.timedelta(days=7),
    "USER_AUTHENTICATION_RULE": "rest_framework_simplejwt.authentication.default_user_authentication_rule",
    "UPDATE_LAST_LOGIN": True,
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': None,
    'JSON_ENCODER': None,
    'JWK_URL': None,
    'LEEWAY': 0,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',
    'JTI_CLAIM': 'jti',
    'SLIDING_TOKEN_REFRESH_EXP_CLAIM': 'refresh_exp',
    'SLIDING_TOKEN_LIFETIME': datetime.timedelta(minutes=5),
    'SLIDING_TOKEN_REFRESH_LIFETIME': datetime.timedelta(days=1),
}


# # Django Allauth settings
# SITE_ID = 1
# ACCOUNT_ADAPTER = 'users.services.CustomAccountAdapter'
# ACCOUNT_LOGIN_METHODS = {'email'}
# ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
# ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
# ACCOUNT_RATE_LIMITS = {
#     'login_failed': '5/5m',
# }
# ACCOUNT_LOGOUT_ON_GET = True
# ACCOUNT_USER_MODEL_USERNAME_FIELD = None


ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"  # new

AUTH_USER_MODEL = "users.User"  # Must match "app_name.ModelName"



# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    }
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles/")
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Cors
# CSRF Settings
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:4000',
    'http://127.0.0.1:4000',
    'http://0.0.0.0:4000',
    'http://localhost:5000',
    'http://127.0.0.1:5000',
    'https://*.replit.dev',
    'https://echo-v1-backend-sh6i.onrender.com',
    "https://letusecho.vercel.app",  # Frontend Local
]
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_COOKIE_HTTPONLY = False  # Allow JavaScript access for SPA
CSRF_USE_SESSIONS = False
CSRF_COOKIE_SAMESITE = 'Lax'


CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]
# CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOWED_ORIGINS = [
   "https://echo-frontend-suave-lads-projects.vercel.app", # Frontend Dev
   "https://prod.d2rhhq8y49f47w.amplifyapp.com", # Frontend Prod
   "https://app.echo.com",  # Frontend Prod
   "http://app.echo.com",  # Frontend Prod
   "http://localhost:3000",  # Frontend Local
   "https://letusecho.vercel.app",  # Frontend Local


]

# Django Spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'ECHO AI API',
    'DESCRIPTION': 'Comprehensive backend API system supporting image OCR translation and voice translation with African language specialization',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'SCHEMA_PATH_PREFIX': '/api/',
    'COMPONENT_SPLIT_REQUEST': True,
    'SORT_OPERATIONS': False,
    'SERVE_AUTHENTICATION': [],
    'SERVE_PERMISSIONS': [],
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
        'docExpansion': 'none',
        'filter': True,
        'showExtensions': True,
        'showCommonExtensions': True,
    },
    'POSTPROCESSING_HOOKS': [],
}


# Scheduled jobs
# ------------------------------------------------------------------------------
REDIS_ENABLED = config("REDIS_HOST", "")

RQ_DEFAULT_QUEUE = "default"
RQ_GENERATOR_QUEUE = "generator"
RQ_SENDER_QUEUE = "sender"

# https://en.wikipedia.org/wiki/Cron
#
# ┌───────────── minute (0 - 59)
# │ ┌───────────── hour (0 - 23)
# │ │ ┌───────────── day of month (1 - 31)
# │ │ │ ┌───────────── month (1 - 12)
# │ │ │ │ ┌───────────── day of week (0 - 6) (Sunday to Saturday;
# │ │ │ │ │                                   7 is also Sunday on some systems)
# │ │ │ │ │
# │ │ │ │ │
# * * * * *

# 0 8 * * 1-5  -> Every working day at 8:00
RQ_CRON_DEFAULT = "0 8 * * 1-5"
RQ_CRON_TASKS = []


# Redis configuration
# ------------------------------------------------------------------------------

if REDIS_ENABLED:
    REDIS_HOST = config("REDIS_HOST")
    REDIS_PORT = int(config("REDIS_PORT", 6379))
    REDIS_DB = int(config("REDIS_DB", 0))
    REDIS_PASSWORD = config("REDIS_PASSWORD")


# Django-RQ configuration
# ------------------------------------------------------------------------------

if REDIS_ENABLED:
    INSTALLED_APPS += ["django_rq"]

    RQ = {
        "DEFAULT_RESULT_TTL": 5000,
    }

    RQ_QUEUES = {
        RQ_DEFAULT_QUEUE: {
            "HOST": REDIS_HOST,
            "PORT": REDIS_PORT,
            "DB": REDIS_DB,
            "PASSWORD": REDIS_PASSWORD,
            "DEFAULT_TIMEOUT": 360,
        },
        RQ_GENERATOR_QUEUE: {
            "HOST": REDIS_HOST,
            "PORT": REDIS_PORT,
            "DB": REDIS_DB,
            "PASSWORD": REDIS_PASSWORD,
            "DEFAULT_TIMEOUT": 360,
        },
        RQ_SENDER_QUEUE: {
            "HOST": REDIS_HOST,
            "PORT": REDIS_PORT,
            "DB": REDIS_DB,
            "PASSWORD": REDIS_PASSWORD,
            "DEFAULT_TIMEOUT": 360,
        },
    }

# Cache configuration
# For local development, we use in-memory cache which is simple and fast.
# For production, you might want to switch the 'default' to use 'redis'.
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    },
    'redis': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': 'redis://127.0.0.1:6379/1',
    }
}


VERIFICATION_OTP_TIMEOUT = int(config("VERIFICATION_OTP_TIMEOUT", "30"))
STRIPE_SECRET_KEY = config("STRIPE_SECRET_KEY")


# Audio file settings
SUPPORTED_AUDIO_FORMATS = [
    'audio/wav',
    'audio/mpeg', 
    'audio/mp4',
    'audio/webm',
    'audio/opus',
    'audio/ogg',
    'audio/m4a'
]

# Maximum audio file size (10MB)
MAX_AUDIO_FILE_SIZE = 10 * 1024 * 1024

# Image file settings
SUPPORTED_IMAGE_FORMATS = [
    'image/jpeg',
    'image/png',
    'image/jpg',
    'image/bmp',
    'image/tiff',
    'image/webp',
    'image/heic',
    'image/avif'
]

# Maximum image file size (10MB)
MAX_IMAGE_FILE_SIZE = 10 * 1024 * 1024

# OTP Settings
OTP_EXPIRY_MINUTES = 10
OTP_LENGTH = 6
