from decouple import config

FRONTEND_BASE_URL = config("FRONTEND_BASE_URL")

FRONTEND_VERIFY_URL = f"{FRONTEND_BASE_URL}/verify"
FRONTEND_RESET_URL = f"{FRONTEND_BASE_URL}/reset-password"

API_DOCUMENTATION_ALLOWED_EMAILS = config("API_DOCUMENTATION_ALLOWED_EMAILS")
