# Generated by Django 5.2.5 on 2025-08-31 11:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudStorageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Configuration name', max_length=100, unique=True)),
                ('provider', models.CharField(choices=[('s3', 'Amazon S3'), ('gcs', 'Google Cloud Storage'), ('azure', 'Azure Blob Storage')], default='s3', max_length=10)),
                ('bucket_name', models.CharField(help_text='Cloud storage bucket name', max_length=255)),
                ('region', models.CharField(default='us-east-1', help_text='Storage region', max_length=50)),
                ('endpoint_url', models.URLField(blank=True, help_text='Custom endpoint URL (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this config is currently active')),
                ('credentials_env_prefix', models.CharField(default='CLOUD_STORAGE', help_text="Environment variable prefix for credentials (e.g., 'CLOUD_STORAGE' looks for CLOUD_STORAGE_ACCESS_KEY)", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_active', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LanguageSupport',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('native_name', models.CharField(max_length=100)),
                ('flag_emoji', models.CharField(default='🌍', max_length=10)),
                ('speech_to_text_supported', models.BooleanField(default=True)),
                ('text_to_speech_supported', models.BooleanField(default=True)),
                ('translation_supported', models.BooleanField(default=True)),
                ('is_african_language', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='voice_settings', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('model', models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-pro', 'Gemini 2.5 Pro')], default='gemini-2.5-flash', max_length=50)),
                ('voice', models.CharField(choices=[('Zephyr', 'Zephyr (English - Neutral)'), ('Nova', 'Nova (English - Female)'), ('Orbit', 'Orbit (English - Male)'), ('Echo', 'Echo (English - Conversational)'), ('Breeze', 'Breeze (English - Calm)'), ('Aria', 'Aria (Multi-language - Female)'), ('Phoenix', 'Phoenix (Multi-language - Male)'), ('Luna', 'Luna (Multi-language - Neutral)')], default='Zephyr', max_length=50)),
                ('autoplay', models.BooleanField(default=False)),
                ('auto_detect_language', models.BooleanField(default=True)),
                ('super_fast_mode', models.BooleanField(default=False)),
                ('source_language', models.CharField(default='auto', max_length=10)),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('theme', models.CharField(default='african', max_length=20)),
                ('audio_quality', models.CharField(default='high', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('original_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('original_audio_url', models.URLField(blank=True, help_text='Cloud storage URL for original audio file', null=True)),
                ('translated_audio_url', models.URLField(blank=True, help_text='Cloud storage URL for translated audio file', null=True)),
                ('original_filename', models.CharField(blank=True, help_text='Original filename of uploaded audio', max_length=255, null=True)),
                ('audio_format', models.CharField(blank=True, help_text='Audio file format (wav, mp3, etc.)', max_length=10, null=True)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('processing_time', models.FloatField(default=0.0)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='audio/')),
                ('audio_type', models.CharField(choices=[('original', 'Original Recording'), ('translated', 'Translated Audio'), ('tts', 'Text-to-Speech')], max_length=20)),
                ('language', models.CharField(max_length=10)),
                ('duration', models.FloatField(default=0.0)),
                ('file_size', models.IntegerField(default=0)),
                ('format', models.CharField(default='wav', max_length=10)),
                ('sample_rate', models.IntegerField(default=44100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('translation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='voice_translator.translation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
