# Generated by Django 5.2.5 on 2026-08-04 07:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_fix_transaction_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_credit', models.IntegerField(default=30, help_text='Initial free credits for new users')),
            ],
            options={
                'verbose_name': 'Global Configuration',
                'verbose_name_plural': 'Global Configuration',
            },
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='transaction',
            name='service_fee',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='withdrawable_amount',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
