# Generated by Django 5.2.5 on 2025-11-08 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagesupport',
            name='text_to_text_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename of uploaded audio', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='translation.translation'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='feature_type',
            field=models.CharField(blank=True, choices=[('REGISTRATION', 'REGISTRATION'), ('RESET PASSWORD', 'RESET PASSWORD'), ('LOGIN', 'LOGIN'), ('SPEECH_TRANSLATION', 'SPEECH_TRANSLATION'), ('SMS_TRANSLATION', 'SMS_TRANSLATION'), ('CALL_TRANSLATION', 'CALL_TRANSLATION')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='original_audio_url',
            field=models.URLField(blank=True, help_text='Cloud storage URL for original audio file', null=True),
        ),
        migrations.AlterField(
            model_name='translationprocessingtime',
            name='speech_to_text',
            field=models.FloatField(default=0.0, help_text='Speech-to-text processing time in seconds'),
        ),
        migrations.AlterField(
            model_name='translationprocessingtime',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_times', to='translation.translation'),
        ),
    ]
