# Generated by Django 5.2.5 on 2026-03-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0002_languagesupport_text_to_text_supported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='file_format',
            field=models.CharField(blank=True, help_text='File format (pdf, docx, etc.)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='original_file_url',
            field=models.URLField(blank=True, help_text='Cloud storage URL for original document/ebook', null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='translated_file_url',
            field=models.URLField(blank=True, help_text='Cloud storage URL for translated document/ebook', null=True),
        ),
        migrations.AlterField(
            model_name='cloudstorageconfig',
            name='provider',
            field=models.CharField(choices=[('s3', 'Amazon S3'), ('gcs', 'Google Cloud Storage'), ('azure', 'Azure Blob Storage'), ('cloudinary', 'Cloudinary')], default='s3', max_length=10),
        ),
        migrations.AlterField(
            model_name='translation',
            name='feature_type',
            field=models.CharField(blank=True, choices=[('SPEECH_TRANSLATION', 'SPEECH_TRANSLATION'), ('IMAGE_TRANSLATION', 'IMAGE_TRANSLATION'), ('SMS_TRANSLATION', 'SMS_TRANSLATION'), ('TEXT_TRANSLATION', 'TEXT_TRANSLATION'), ('CALL_TRANSLATION', 'CALL_TRANSLATION'), ('EBOOK_TRANSLATION', 'EBOOK_TRANSLATION')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='translation',
            name='original_filename',
            field=models.CharField(blank=True, help_text='Original filename of uploaded file', max_length=255, null=True),
        ),
    ]
