# Generated by Django 5.2.5 on 2026-03-20 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0003_translation_file_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='error_message',
            field=models.TextField(blank=True, help_text='Error message if translation failed', null=True),
        ),
        migrations.AddField(
            model_name='translation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', help_text='Status of the translation process', max_length=20),
        ),
    ]
