# Generated by Django 5.2.5 on 2026-03-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0004_translation_error_message_translation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='original_file',
            field=models.FileField(blank=True, null=True, upload_to='translation/document/input/'),
        ),
        migrations.AddField(
            model_name='translation',
            name='translated_file',
            field=models.FileField(blank=True, null=True, upload_to='translation/document/output/'),
        ),
    ]
