# Generated by Django 5.2.5 on 2026-03-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0005_translation_original_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='mode',
            field=models.CharField(choices=[('SHORT', 'Short (Synchronous)'), ('LARGE', 'Large (Asynchronous)')], default='SHORT', help_text='Translation mode (SHORT or LARGE)', max_length=10),
        ),
    ]
