# Generated by Django 5.2.5 on 2026-03-20 21:02

import core.model
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0006_translation_mode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='languagesupport',
            old_name='translation_supported',
            new_name='document_translation_supported',
        ),
        migrations.AddField(
            model_name='languagesupport',
            name='image_translation_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='languagesupport',
            name='speech_to_speech_translation_supported',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ImageTranslation',
            fields=[
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_language', models.CharField(default='auto', max_length=10)),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('mode', models.CharField(choices=[('SHORT', 'Short (Synchronous)'), ('LARGE', 'Large (Asynchronous)')], default='SHORT', max_length=10)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_processing_time', models.FloatField(default=0.0)),
                ('original_image', models.ImageField(upload_to='translations/images/original/')),
                ('ocr_text', models.TextField(blank=True, null=True)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Image Translations',
                'ordering': ['-date_created'],
                'abstract': False,
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
        migrations.RenameModel(
            old_name='TranslationProcessingTime',
            new_name='SpeechTranslationProcessingTime',
        ),
        migrations.CreateModel(
            name='SpeechTranslation',
            fields=[
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_language', models.CharField(default='auto', max_length=10)),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('mode', models.CharField(choices=[('SHORT', 'Short (Synchronous)'), ('LARGE', 'Large (Asynchronous)')], default='SHORT', max_length=10)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_processing_time', models.FloatField(default=0.0)),
                ('original_audio', models.FileField(blank=True, null=True, upload_to='translation/speech/input/')),
                ('translated_audio', models.FileField(blank=True, null=True, upload_to='translation/speech/output/')),
                ('original_audio_url', models.URLField(blank=True, null=True)),
                ('translated_audio_url', models.URLField(blank=True, null=True)),
                ('original_text', models.TextField(blank=True, null=True)),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('audio_format', models.CharField(blank=True, max_length=10, null=True)),
                ('duration', models.FloatField(default=0.0)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('speech_service', models.CharField(choices=[('STS', 'Speech to Speech'), ('STT', 'Speech to Text'), ('TTS', 'Text to Speech')], default='STS', max_length=10)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='translation.speechtranslation'),
        ),
        migrations.AlterField(
            model_name='speechtranslationprocessingtime',
            name='translation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processing_times', to='translation.speechtranslation'),
        ),
        migrations.CreateModel(
            name='TextTranslation',
            fields=[
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('original_language', models.CharField(default='auto', max_length=10)),
                ('target_language', models.CharField(default='en', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('mode', models.CharField(choices=[('SHORT', 'Short (Synchronous)'), ('LARGE', 'Large (Asynchronous)')], default='SHORT', max_length=10)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('total_processing_time', models.FloatField(default=0.0)),
                ('original_text', models.TextField()),
                ('translated_text', models.TextField(blank=True, null=True)),
                ('is_sms', models.BooleanField(default=False, help_text='Whether this is an SMS translation')),
                ('original_file_url', models.URLField(blank=True, null=True)),
                ('translated_file_url', models.URLField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_translations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_created'],
                'abstract': False,
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
        migrations.CreateModel(
            name='LLMLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=50)),
                ('model_name', models.CharField(max_length=100)),
                ('function_performed', models.CharField(max_length=50)),
                ('input_tokens', models.IntegerField(default=0)),
                ('output_tokens', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('latency', models.FloatField(default=0.0)),
                ('cost', models.DecimalField(decimal_places=6, default=0.0, max_digits=10)),
                ('status', models.CharField(default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('image_translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_logs', to='translation.imagetranslation')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('speech_translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_logs', to='translation.speechtranslation')),
                ('text_translation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='llm_logs', to='translation.texttranslation')),
            ],
            options={
                'verbose_name': 'LLM Usage Log',
                'verbose_name_plural': 'LLM Usage Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Translation',
        ),
    ]
