# Generated by Django 5.2.5 on 2026-06-06 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0007_rename_translation_supported_languagesupport_document_translation_supported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetranslation',
            name='original_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='model',
            field=models.CharField(choices=[('gemini-2.5-flash-preview-tts', 'Gemini 2.5 Flash (TTS)'), ('gemini-2.5-pro-preview-tts', 'Gemini 2.5 Pro (TTS)'), ('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-1.5-flash', 'Gemini 1.5 Flash')], default='gemini-2.5-flash', max_length=50),
        ),
    ]
