# Generated by Django 5.2.5 on 2026-06-14 12:56

import core.model
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0009_texttranslation_nullable_text_longer_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousTrial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_id', models.CharField(blank=True, max_length=255, null=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_used', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Anonymous Trial',
                'verbose_name_plural': 'Anonymous Trials',
                'ordering': ['-last_used'],
            },
            bases=(models.Model, core.model.DictUpdateMixin),
        ),
    ]
