# Generated by Django 5.2.5 on 2026-06-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0010_anonymoustrial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetranslation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra metadata like token usage, cost, model versions'),
        ),
        migrations.AddField(
            model_name='imagetranslation',
            name='processing_steps',
            field=models.JSONField(blank=True, default=dict, help_text='Time tracking per step (e.g. STT, TTS, Translation)'),
        ),
        migrations.AddField(
            model_name='speechtranslation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra metadata like token usage, cost, model versions'),
        ),
        migrations.AddField(
            model_name='speechtranslation',
            name='processing_steps',
            field=models.JSONField(blank=True, default=dict, help_text='Time tracking per step (e.g. STT, TTS, Translation)'),
        ),
        migrations.AddField(
            model_name='texttranslation',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Extra metadata like token usage, cost, model versions'),
        ),
        migrations.AddField(
            model_name='texttranslation',
            name='processing_steps',
            field=models.JSONField(blank=True, default=dict, help_text='Time tracking per step (e.g. STT, TTS, Translation)'),
        ),
    ]
