# Generated by Django 5.2.5 on 2026-06-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0011_imagetranslation_metadata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetranslation',
            name='billing_cost_deducted',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost deducted from wallet', max_digits=14),
        ),
        migrations.AddField(
            model_name='imagetranslation',
            name='billing_currency_used',
            field=models.CharField(default='CREDITS', help_text='CREDITS or USD', max_length=10),
        ),
        migrations.AddField(
            model_name='imagetranslation',
            name='channel',
            field=models.CharField(default='UI', help_text='UI or API', max_length=10),
        ),
        migrations.AddField(
            model_name='imagetranslation',
            name='units_processed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='e.g. Minutes, Pages, or Million Characters', max_digits=14),
        ),
        migrations.AddField(
            model_name='speechtranslation',
            name='billing_cost_deducted',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost deducted from wallet', max_digits=14),
        ),
        migrations.AddField(
            model_name='speechtranslation',
            name='billing_currency_used',
            field=models.CharField(default='CREDITS', help_text='CREDITS or USD', max_length=10),
        ),
        migrations.AddField(
            model_name='speechtranslation',
            name='channel',
            field=models.CharField(default='UI', help_text='UI or API', max_length=10),
        ),
        migrations.AddField(
            model_name='speechtranslation',
            name='units_processed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='e.g. Minutes, Pages, or Million Characters', max_digits=14),
        ),
        migrations.AddField(
            model_name='texttranslation',
            name='billing_cost_deducted',
            field=models.DecimalField(decimal_places=6, default=0, help_text='Cost deducted from wallet', max_digits=14),
        ),
        migrations.AddField(
            model_name='texttranslation',
            name='billing_currency_used',
            field=models.CharField(default='CREDITS', help_text='CREDITS or USD', max_length=10),
        ),
        migrations.AddField(
            model_name='texttranslation',
            name='channel',
            field=models.CharField(default='UI', help_text='UI or API', max_length=10),
        ),
        migrations.AddField(
            model_name='texttranslation',
            name='units_processed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='e.g. Minutes, Pages, or Million Characters', max_digits=14),
        ),
    ]
