# Generated by Django 6.0.6 on 2026-06-14 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0012_imagetranslation_billing_cost_deducted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='languagesupport',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether this language is currently active for translations'),
        ),
    ]
