# Generated by Django 6.0.6 on 2026-06-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation', '0013_languagesupport_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetranslation',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Whether the user has favorited this translation'),
        ),
        migrations.AddField(
            model_name='speechtranslation',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Whether the user has favorited this translation'),
        ),
        migrations.AddField(
            model_name='texttranslation',
            name='is_favorite',
            field=models.BooleanField(default=False, help_text='Whether the user has favorited this translation'),
        ),
    ]
